# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e36-TRIAen-aJ7CmHup6-SKLBjojv2F6
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

url = "https://sbm.gov.in/sbmgdashboard/statesdashboard.aspx"

response = requests.get(
    url,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=30
)

response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")

# Get clean text
lines = [
    re.sub(r"\s+", " ", x).strip()
    for x in soup.get_text("\n").splitlines()
    if x.strip()
]


# =========================================================
# FUNCTIONS
# =========================================================

def is_number(text):
    return bool(
        re.fullmatch(
            r"\+?\s*[\d,]+(?:\.\d+)?\s*\*?",
            text.strip()
        )
    )


def clean_number(text):
    return re.sub(r"[+,* ]", "", text)


def get_values_after(lines, index, count=4):
    """
    Get consecutive numeric values after an indicator.

    Example:
        ODF Plus Villages
        +32 *
        569,726

    returns:
        Change = +32
        Total  = 569726
    """

    values = []

    for x in lines[index + 1:index + 1 + count]:

        if is_number(x):
            values.append(x)

        elif values:
            break

    change = ""
    total = ""

    if len(values) >= 2:

        # First number is change
        change = clean_number(values[0])

        # Second number is total
        total = clean_number(values[1])

    elif len(values) == 1:

        total = clean_number(values[0])

    return change, total


# =========================================================
# DATA STORAGE
# =========================================================

data = []


def add(indicator, change, total):

    data.append({
        "Indicator": indicator,
        "Change": change,
        "Total": total
    })


# =========================================================
# FIRST SUMMARY SECTION
# =========================================================

# These are UNIQUE labels
unique_metrics = [
    "Total Districts",
    "Total Blocks",
    "Total Gram Panchayats",
    "SBM Villages",
    "ODF Plus Villages",
    "Villages having arrangement of Solid Waste Management",
    "Villages having arrangement of Liquid Waste Management",
    "Community Compost pits",
    "Waste collection & Segregation sheds",
    "Vehicles for collection and Transportation of waste",
    "Community Soak/Leach/Magic pits",
    "Drainage facility",
    "Phytorid/ DEWATS/ Wetlands/ Duckweed Pond",
    "WSP 3/5 Pond System",
    "Faecal Sludge Management Plant",
    "Plastic Waste Management Unit",
    "Community Sanitary Complexes",
    "Household Toilets constructed",
    "Soak/Leach/Magic Pit at HH Level",
    "Kitchen Garden at HH Level",
    "Bio gas plants at HH Level",
    "Compost Pits at HH Level"
]


for metric in unique_metrics:

    for i, line in enumerate(lines):

        if line.lower() == metric.lower():

            change, total = get_values_after(lines, i)

            if total:

                add(
                    metric,
                    change,
                    total
                )

            break


# =========================================================
# ODF PLUS MODEL VERIFICATION
# =========================================================

# Find every occurrence of "ODF Plus Model"
model_indexes = [
    i for i, line in enumerate(lines)
    if line.lower() == "odf plus model"
]


# First occurrence = normal ODF Plus Model
if len(model_indexes) >= 1:

    i = model_indexes[0]

    change, total = get_values_after(lines, i)

    add(
        "ODF Plus Model",
        change,
        total
    )


# Find verification labels directly
for i, line in enumerate(lines):

    if "1st Verfication" in line:

        change, total = get_values_after(lines, i)

        if total:
            add(
                "ODF Plus Model (1st Verfication)",
                change,
                total
            )


    elif "2nd Verfication" in line:

        change, total = get_values_after(lines, i)

        if total:
            add(
                "ODF Plus Model (2nd Verfication)",
                change,
                total
            )


# =========================================================
# DISTRICTS
# =========================================================

for i, line in enumerate(lines):

    if line.lower() == "districts":

        # Find ODF Plus
        for j in range(i + 1, min(i + 10, len(lines))):

            if lines[j].lower() == "odf plus":

                if j + 1 < len(lines) and is_number(lines[j + 1]):

                    add(
                        "Districts - ODF Plus",
                        "",
                        clean_number(lines[j + 1])
                    )

            if lines[j].lower() == "odf plus model":

                if j + 1 < len(lines) and is_number(lines[j + 1]):

                    add(
                        "Districts - ODF Plus Model",
                        "",
                        clean_number(lines[j + 1])
                    )

        break


# =========================================================
# BLOCKS
# =========================================================

for i, line in enumerate(lines):

    if line.lower() == "blocks":

        for j in range(i + 1, min(i + 10, len(lines))):

            if lines[j].lower() == "odf plus":

                if j + 1 < len(lines) and is_number(lines[j + 1]):

                    add(
                        "Blocks - ODF Plus",
                        "",
                        clean_number(lines[j + 1])
                    )

            if lines[j].lower() == "odf plus model":

                if j + 1 < len(lines) and is_number(lines[j + 1]):

                    add(
                        "Blocks - ODF Plus Model",
                        "",
                        clean_number(lines[j + 1])
                    )

        break


# =========================================================
# GRAM PANCHAYATS
# =========================================================

for i, line in enumerate(lines):

    if line.lower() == "gram panchyats":

        for j in range(i + 1, min(i + 10, len(lines))):

            if lines[j].lower() == "odf plus":

                if j + 1 < len(lines) and is_number(lines[j + 1]):

                    add(
                        "Gram Panchyats - ODF Plus",
                        "",
                        clean_number(lines[j + 1])
                    )

            if lines[j].lower() == "odf plus model":

                if j + 1 < len(lines) and is_number(lines[j + 1]):

                    add(
                        "Gram Panchyats - ODF Plus Model",
                        "",
                        clean_number(lines[j + 1])
                    )

        break


# =========================================================
# BIOGAS
# =========================================================

for i, line in enumerate(lines):

    if line.lower() == "total number of biogas plants (sbm-g)":

        for j in range(i + 1, min(i + 10, len(lines))):

            if lines[j].lower() == "registered":

                if j + 1 < len(lines):

                    add(
                        "Total Number of Biogas Plants (SBM-G) Registered",
                        "",
                        clean_number(lines[j + 1])
                    )

            elif lines[j].lower() == "functional":

                if j + 1 < len(lines):

                    add(
                        "Total Number of Biogas Plants (SBM-G) Functional",
                        "",
                        clean_number(lines[j + 1])
                    )

        break


# =========================================================
# REMOVE DUPLICATES
# =========================================================

df = pd.DataFrame(data)

df = df.drop_duplicates(
    subset=["Indicator"],
    keep="first"
).reset_index(drop=True)



from datetime import datetime
df = df[["Indicator", "Total"]]

current_datetime = datetime.now().strftime("%d-%m-%Y %H:%M:%S")

# Add Date as the first row
date_row = pd.DataFrame({
    "Indicator": ["Date"],
    "Total": [current_datetime]
})

df = pd.concat(
    [date_row, df],
    ignore_index=True
)
df

desired_order = [
    "Date",

    "Total Districts",
    "Districts - ODF Plus",
    "Districts - ODF Plus Model",

    "Total Blocks",
    "Blocks - ODF Plus",
    "Blocks - ODF Plus Model",

    "Total Gram Panchayats",
    "Gram Panchyats - ODF Plus",
    "Gram Panchyats - ODF Plus Model",

    "SBM Villages",
    "ODF Plus Villages",
    "ODF Plus Model",
    "ODF Plus Model (1st Verfication)",
    "ODF Plus Model (2nd Verfication)",

    "Villages having arrangement of Solid Waste Management",
    "Villages having arrangement of Liquid Waste Management",

    "Community Compost pits",
    "Waste collection & Segregation sheds",
    "Vehicles for collection and Transportation of waste",
    "Community Soak/Leach/Magic pits",
    "Drainage facility",
    "Phytorid/ DEWATS/ Wetlands/ Duckweed Pond",
    "WSP 3/5 Pond System",

    "Total Number of Biogas Plants (SBM-G) Registered",
    "Total Number of Biogas Plants (SBM-G) Functional",

    "Faecal Sludge Management Plant",
    "Plastic Waste Management Unit",
    "Community Sanitary Complexes",
    "Household Toilets constructed",

    "Soak/Leach/Magic Pit at HH Level",
    "Kitchen Garden at HH Level",
    "Bio gas plants at HH Level",
    "Compost Pits at HH Level"
]
df["sort_order"] = df["Indicator"].map(
    {name: i for i, name in enumerate(desired_order)}
)
df = (
    df.sort_values("sort_order")
      .drop(columns="sort_order")
      .reset_index(drop=True)
)

df

df = df[["Indicator", "Total"]]
df_transposed = df.set_index("Indicator").T
df_transposed

import gspread
from google.colab import auth
from google.auth import default

# Authenticate
auth.authenticate_user()

creds, _ = default()
gc = gspread.authorize(creds)

# Open Google Sheet
spreadsheet = gc.open_by_key(
    "1Uj72MCqn26u6v0A_g720k_sXg2OJQ1nR2VeNOlMCH60"
)

# First sheet/tab
worksheet = spreadsheet.sheet1


# =========================================================
# PREPARE DATA
# =========================================================

headers = df_transposed.columns.tolist()
row = df_transposed.iloc[0].tolist()


# =========================================================
# FIND NEXT EMPTY ROW
# =========================================================

existing_data = worksheet.get_all_values()

if not existing_data:

    # Completely empty sheet
    next_row = 1

    # Add headers
    worksheet.update(
        f"A{next_row}",
        [headers],
        value_input_option="USER_ENTERED"
    )

    # Add data below headers
    worksheet.update(
        f"A{next_row + 1}",
        [row],
        value_input_option="USER_ENTERED"
    )

else:

    # Next row after existing data
    next_row = len(existing_data) + 1

    # If headers don't exist, add them
    if next_row == 1:
        worksheet.update(
            f"A1",
            [headers],
            value_input_option="USER_ENTERED"
        )
        next_row = 2

    # Write data into the next row
    worksheet.update(
        f"A{next_row}",
        [row],
        value_input_option="USER_ENTERED"
    )


print(f"✅ Data pushed to row {next_row}")

